version: "3.7"

services:
  front:
    build:
      context: .
      dockerfile: ./build/todo-front/Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - backend-vol:/var/www/back
      - "./build/todo-front/conf/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
    links:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./build/todo-back/Dockerfile
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgre
      - DB_DATABASE=db_todo
      - DB_USERNAME=violin
      - DB_PASSWORD=passwd
    volumes:
      - backend-vol:/var/www/back
      - "./build/todo-back/conf/default.php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - postgre

  postgre:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db_todo
      - POSTGRES_USER=violin
      - POSTGRES_PASSWORD=passwd

volumes:
  backend-vol:
